version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "opensmsgw/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "opensmsgw/build.gradle" }}
      - run: echo "$ENCODED_KEYSTORE" | base64 --decode >> ${HOME}/code/keystore.jks
      - run: echo 'export KEYSTORE=${HOME}/code/keystore.jks' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Build
          command: ./gradlew build
      - run:
          name: Make APK
          command: ./gradlew packageRelease
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: opensmsgw/build/reports
          destination: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: opensmsgw/build/outputs/apk/release
          destination: apk
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: opensmsgw/build/test-results
